from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path
import sys
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts._analysis_common import DEFAULT_CSV_ROOT
from scripts._analysis_common import ensure_dir


DEFAULT_FOCUS_CIRCUITS = (
    "barenco_tof_4",
    "hwb_6",
    "gf_2pow2_mult",
    "qft_4",
)


def load_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def coerce_float(value: Any) -> float | None:
    if value in (None, "", "None"):
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def coerce_int(value: Any) -> int | None:
    value_float = coerce_float(value)
    return None if value_float is None else int(value_float)


def fmt_float(value: Any, digits: int = 3) -> str:
    value_float = coerce_float(value)
    return "" if value_float is None else f"{value_float:.{digits}f}"


def fmt_int(value: Any) -> str:
    value_int = coerce_int(value)
    return "" if value_int is None else str(value_int)


def tex_texttt(value: str) -> str:
    return r"\texttt{" + value.replace("_", r"\_") + "}"


def ok_rows(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    return [row for row in rows if row.get("status") == "ok"]


def relation_counts(rows: list[dict[str, str]], field: str) -> dict[str, int]:
    values = [row.get(field) for row in ok_rows(rows)]
    return {
        "better": values.count("better"),
        "tie": values.count("tie"),
        "worse": values.count("worse"),
    }


def first_float(rows: list[dict[str, str]], field: str, default: float = 0.0) -> float:
    for row in ok_rows(rows):
        value = coerce_float(row.get(field))
        if value is not None:
            return value
    return default


def sha256_file(path: Path) -> str | None:
    if not path.exists():
        return None
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def selected_focus_rows(
    rows: list[dict[str, str]],
    focus_circuits: tuple[str, ...],
) -> list[dict[str, str]]:
    by_circuit = {row["circuit_id"]: row for row in ok_rows(rows)}
    return [
        by_circuit[circuit_id]
        for circuit_id in focus_circuits
        if circuit_id in by_circuit
    ]


def render_guard_table(
    rows: list[dict[str, str]],
    *,
    focus_circuits: tuple[str, ...] = DEFAULT_FOCUS_CIRCUITS,
) -> str:
    selected = selected_focus_rows(rows, focus_circuits)
    aggressive_counts = relation_counts(rows, "aggressive_relation_vs_conservative")
    guarded_counts = relation_counts(rows, "guarded_relation_vs_conservative")
    qasm_threshold = first_float(rows, "guarded_qasm_depth_gain_threshold")
    mixed_threshold = first_float(rows, "guarded_mixed_drop_fraction_threshold")

    lines = [
        "% Generated by scripts/export_paper_tensor_v3_guard_table.py.",
        "% Source: results/csv/tensor_v3_profile_comparison.csv.",
        r"\begin{table*}[t]",
        (
            r"\caption{Tensor-v3 profile comparison for representative expanded "
            r"benchmarks. Lower $\primarync$ is better. The guarded selector uses "
            rf"$\tau_d={qasm_threshold:.2f}$ and $\tau_m={mixed_threshold:g}$. "
            rf"Across the full audit set, aggressive B/T/W is "
            rf"{aggressive_counts['better']}/{aggressive_counts['tie']}/{aggressive_counts['worse']} "
            rf"and guarded B/T/W is "
            rf"{guarded_counts['better']}/{guarded_counts['tie']}/{guarded_counts['worse']}.}}"
        ),
        r"\label{tab:tensor-v3-guard}",
        r"\centering",
        r"\small",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        (
            r"Circuit & $T_{\mathrm{cons}}$ & $T_{\mathrm{aggr}}$ & "
            r"$T_{\mathrm{guard}}$ & $\primarync^{\mathrm{cons}}$ & "
            r"$\primarync^{\mathrm{aggr}}$ & $\primarync^{\mathrm{guard}}$\\"
        ),
        r"\midrule",
    ]
    for row in selected:
        lines.append(
            " & ".join(
                [
                    tex_texttt(row["circuit_id"]),
                    fmt_int(row.get("conservative_tcount")),
                    fmt_int(row.get("aggressive_tcount")),
                    fmt_int(row.get("guarded_tcount")),
                    fmt_float(row.get("conservative_primary_nc_depth_ratio")),
                    fmt_float(row.get("aggressive_primary_nc_depth_ratio")),
                    fmt_float(row.get("guarded_primary_nc_depth_ratio")),
                ]
            )
            + r"\\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table*}",
            "",
        ]
    )
    return "\n".join(lines)


def write_table(table_text: str, output_path: Path) -> Path:
    ensure_dir(output_path.parent)
    output_path.write_text(table_text, encoding="utf-8")
    return output_path


def build_manifest(
    rows: list[dict[str, str]],
    *,
    comparison_csv: Path,
    output_tex: Path,
    focus_circuits: tuple[str, ...],
    output_tex_sha256: str | None = None,
) -> dict[str, Any]:
    selected = selected_focus_rows(rows, focus_circuits)
    return {
        "generated_by": "scripts/export_paper_tensor_v3_guard_table.py",
        "comparison_csv": str(comparison_csv),
        "comparison_csv_sha256": sha256_file(comparison_csv),
        "output_tex": str(output_tex),
        "output_tex_sha256": output_tex_sha256 or sha256_file(output_tex),
        "focus_circuits": list(focus_circuits),
        "num_rows": len(rows),
        "num_ok_rows": len(ok_rows(rows)),
        "guarded_qasm_depth_gain_threshold": first_float(
            rows,
            "guarded_qasm_depth_gain_threshold",
        ),
        "guarded_mixed_drop_fraction_threshold": first_float(
            rows,
            "guarded_mixed_drop_fraction_threshold",
        ),
        "aggressive_relation_counts": relation_counts(
            rows,
            "aggressive_relation_vs_conservative",
        ),
        "guarded_relation_counts": relation_counts(
            rows,
            "guarded_relation_vs_conservative",
        ),
        "selected_rows": [
            {
                "circuit_id": row["circuit_id"],
                "conservative_tcount": coerce_int(row.get("conservative_tcount")),
                "aggressive_tcount": coerce_int(row.get("aggressive_tcount")),
                "guarded_tcount": coerce_int(row.get("guarded_tcount")),
                "conservative_primary_nc_depth_ratio": coerce_float(
                    row.get("conservative_primary_nc_depth_ratio")
                ),
                "aggressive_primary_nc_depth_ratio": coerce_float(
                    row.get("aggressive_primary_nc_depth_ratio")
                ),
                "guarded_primary_nc_depth_ratio": coerce_float(
                    row.get("guarded_primary_nc_depth_ratio")
                ),
                "guarded_uses_aggressive": coerce_int(
                    row.get("guarded_uses_aggressive")
                ),
            }
            for row in selected
        ],
    }


def manifest_json(manifest: dict[str, Any]) -> str:
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def write_manifest(manifest: dict[str, Any], output_path: Path) -> Path:
    ensure_dir(output_path.parent)
    output_path.write_text(manifest_json(manifest), encoding="utf-8")
    return output_path


def check_outputs(
    *,
    expected_table_text: str,
    expected_manifest: dict[str, Any],
    output_tex: Path,
    output_json: Path,
) -> dict[str, Any]:
    expected_manifest_text = manifest_json(expected_manifest)
    table_current = (
        output_tex.exists()
        and output_tex.read_text(encoding="utf-8") == expected_table_text
    )
    manifest_current = (
        output_json.exists()
        and output_json.read_text(encoding="utf-8") == expected_manifest_text
    )
    return {
        "ok": table_current and manifest_current,
        "table_current": table_current,
        "manifest_current": manifest_current,
        "output_tex": str(output_tex),
        "output_json": str(output_json),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export the tensor-v3 guarded profile table used by paper/main.tex."
    )
    parser.add_argument(
        "--comparison-csv",
        type=Path,
        default=DEFAULT_CSV_ROOT / "tensor_v3_profile_comparison.csv",
    )
    parser.add_argument(
        "--output-tex",
        type=Path,
        default=REPO_ROOT / "paper" / "tables" / "tensor_v3_guard_table.tex",
    )
    parser.add_argument(
        "--output-json",
        type=Path,
        default=REPO_ROOT / "paper" / "tables" / "tensor_v3_guard_table.json",
    )
    parser.add_argument(
        "--focus-circuit",
        action="append",
        dest="focus_circuits",
        default=None,
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the existing table or manifest differs from regenerated output.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rows = load_csv_rows(args.comparison_csv)
    focus_circuits = (
        tuple(args.focus_circuits) if args.focus_circuits else DEFAULT_FOCUS_CIRCUITS
    )
    table_text = render_guard_table(rows, focus_circuits=focus_circuits)
    manifest = build_manifest(
        rows,
        comparison_csv=args.comparison_csv,
        output_tex=args.output_tex,
        focus_circuits=focus_circuits,
        output_tex_sha256=sha256_text(table_text),
    )
    if args.check:
        check_result = check_outputs(
            expected_table_text=table_text,
            expected_manifest=manifest,
            output_tex=args.output_tex,
            output_json=args.output_json,
        )
        print(json.dumps(check_result, indent=2, sort_keys=True))
        return 0 if check_result["ok"] else 1

    table_path = write_table(table_text, args.output_tex)
    manifest_path = write_manifest(manifest, args.output_json)
    print(
        json.dumps(
            {
                "comparison_csv": str(args.comparison_csv),
                "output_tex": str(table_path),
                "output_json": str(manifest_path),
                "focus_circuits": list(focus_circuits),
                "num_rows": len(rows),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
